### ISSUE TITLE
Mutation names

### ISSUE THREAD

**Issue by mcewenrk** [alkodsi/ctDNAtools#4]
Hello,
I've been working with mutations in get_fragment_size and have found that mapping the output back to the original mutation in the input file makes interpretation difficult. I have been looking at get_mutations_read_names and can see that there is an ID for the mutation (chr14:106327474_C_G in the example below) which, if included in the output, could be used to relate to the input mutations.
An alternative option I thought would be to add an additional field in the mutations input e.g. "MUT.NAME" which, if it were something explanatory like "KRAS G12C", and could also be included in the resulting output would be more informative than the read IDs for downstream analyses.

I have been trying to modify get_fragment_size to allow a mutation ID to be carried through and included in the output but haven't been able to make any progress. Do you think this is feasible and would you have any suggestions please.

get_mutations_read_names(bam = bamT1, mutations = mutations[1:3, ])
#> $`chr14:106327474_C_G`
#> $`chr14:106327474_C_G`$ref
#>   [1] "T1_Library1:1954851" "T1_Library1:1955625" "T1_Library1:1956206" 
...

Thanks

**Comment by alkodsi** [comment]
Hi,

I think what you are looking for is already implemented in get_mutations_fragment_size()

Please let me know if this is what you need or I misinterpreted your question

**Comment by mcewenrk** [comment]
Yes; I think that is it (although it might be nice to be able to specify a name for the mutation like the gene and amino acid change).
Apologies; I wasn't aware of that function - I had been referring to the vignette but hadn't thought to look in the references.
Thank you!

**Comment by alkodsi** [comment]
The function returns a named list with the names being the mutation ID i.e. chr:pos_ref_alt. This should be very easy to map to the names you have for your mutations. Since there is no standard way to name a mutation, I prefer to keep it this way in the package.
Please feel free to reopen if you have other questions.

**Comment by mcewenrk** [comment]
Thank you - yes I quite agree - the instant I hit "post" on my comment I thought it wasn't necessary and would be trivial to join additional annotation.
Thanks
