### ISSUE TITLE
NGS panel used

### ISSUE THREAD

**Issue by Tato14** [alkodsi/ctDNAtools#7]
Thanks for the great tool.

I saw in one of your [publications](https://pubmed.ncbi.nlm.nih.gov/34932792/) that the panels you used are capture based. I was wondering if `ctDNAtools` methods could be used with amplicon based NGS panels.

**Comment by alkodsi** [comment]
HI @Tato14 
There is nothing preventing the functions from working on bam files produced on an amplicon based panels. However, the results may or may not be meaningful depending on the analysis workflow you follow.
